# Generated by Django 4.0.5 on 2022-07-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_author_alter_task_options_alter_task_is_finished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
