# Generated by Django 4.0.5 on 2022-07-04 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_task_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='amount',
        ),
    ]
