# Generated by Django 4.0.5 on 2022-07-07 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_alter_user_options_remove_task_text_task_decription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='decription',
            new_name='description',
        ),
    ]
